[build]
  base = "sat-math/frontend"
  command = "npm ci && npm run build"
  publish = "dist"

[context.production.environment]
  VITE_API_BASE = "https://dsat-math.onrender.com"

[context.deploy-preview.environment]
  VITE_API_BASE = "https://dsat-math.onrender.com"

[context.branch-deploy.environment]
  VITE_API_BASE = "https://dsat-math.onrender.com"


